import { DocumentSlot, DocumentSlotType } from "@/types/tax";

export const createDocumentSlots = (): DocumentSlot[] => [
  {
    type: "FORM_16",
    name: "Form 16 (Part A and Part B)",
    icon: "📋",
    description: "Salary breakdown, HRA, allowances, employer-deducted TDS, exemptions your employer applied",
    badge: "Recommended",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "AIS_TIS",
    name: "AIS / TIS (Annual Information Statement)",
    icon: "📊",
    description: "All TDS credits, high-value transactions the government knows about, advance tax, dividend income reported",
    badge: "Strongly Recommended",
    accepts: [".pdf"],
    infoBox: "📥 How to download your AIS: Login to incometax.gov.in → Click 'e-File' in top menu → 'Income Tax Returns' → 'View AIS' → Click 'Download' → Choose PDF → Upload here. This is the most important document for accurate reconciliation.",
    files: [],
  },
  {
    type: "BANK_STATEMENT",
    name: "Bank Account Statements (All Banks)",
    icon: "🏦",
    description: "Every credit (income) and debit (expense/investment) — AI classifies each transaction",
    badge: "Recommended",
    accepts: [".pdf", ".xlsx", ".xls", ".csv"],
    note: "Upload statements from ALL your bank accounts. Multiple files accepted.",
    files: [],
  },
  {
    type: "CAPITAL_GAINS",
    name: "Capital Gains Statement",
    icon: "📈",
    description: "STCG, LTCG, intraday P&L, F&O income, mutual fund gains, FMV as on 31.01.2018 for pre-2018 holdings",
    badge: "Optional",
    accepts: [".pdf", ".xlsx", ".xls"],
    note: "Available from your broker: Zerodha → Reports → Tax P&L. Groww → Tax → Tax Statement.",
    files: [],
  },
  {
    type: "PAY_SLIPS",
    name: "Pay Slips",
    icon: "💰",
    description: "Monthly salary structure — Basic, HRA, allowances, PF deduction, professional tax",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "HOME_EDUCATION_LOAN",
    name: "Home Loan / Education Loan Interest Certificate",
    icon: "🏠",
    description: "Principal repaid this year (Section 80C), interest paid (Section 24b home / Section 80E education)",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    note: "Usually provided by your bank annually.",
    files: [],
  },
  {
    type: "FD_SAVINGS_INTEREST",
    name: "FD / Savings Bank Interest Certificate",
    icon: "🏧",
    description: "Interest income earned on FDs, RDs, savings account — and TDS already deducted",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "INSURANCE_PREMIUM",
    name: "Life Insurance / Health Insurance Premium Receipts",
    icon: "🛡️",
    description: "Premium amount, policy type, who is insured — for Section 80C and Section 80D deductions",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "DONATION_RECEIPTS",
    name: "Donation Receipts",
    icon: "🤲",
    description: "Amount donated, organisation name, registration number — for Section 80G deduction at 50% or 100%",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "PROPERTY_SALE",
    name: "Property Sale Documents",
    icon: "🏗️",
    description: "Purchase cost, improvement expenses, sale price, stamp duty value — for capital gains computation",
    badge: "Optional",
    accepts: [".pdf", ".jpg", ".jpeg", ".png"],
    files: [],
  },
  {
    type: "PREVIOUS_ITR",
    name: "Previous Year ITR / Acknowledgment",
    icon: "📜",
    description: "Losses carried forward from prior years, Section 54 exemption claims, prior regime choice",
    badge: "Optional",
    accepts: [".pdf", ".xml"],
    note: "Download from incometax.gov.in → e-File → Income Tax Returns → View Filed Returns.",
    files: [],
  },
  {
    type: "OTHER_DOCUMENTS",
    name: "Other Documents",
    icon: "📁",
    description: "Anything tax-relevant — AI will identify and classify",
    badge: "Optional",
    accepts: [".pdf", ".xlsx", ".xls", ".csv", ".jpg", ".jpeg", ".png"],
    files: [],
  },
];

export const SUGGESTION_CHIPS = [
  "All UPI credits = freelancing income",
  "I paid ₹___ rent/month in [city]",
  "I have a home loan — property is self-occupied",
  "Some credits are gifts / family transfers",
  "I have losses carried forward from last year",
  "Apply Section 44ADA (I'm a professional)",
  "Credits from MANDI/APMC = agricultural income",
  "Dream11/gaming credits = online game winnings",
];

export const AY_OPTIONS: { value: string; label: string; period: string }[] = [
  { value: "AY 2026-27", label: "AY 2026-27", period: "Income earned: April 2025 – March 2026" },
  { value: "AY 2025-26", label: "AY 2025-26", period: "Income earned: April 2024 – March 2025" },
  { value: "AY 2024-25", label: "AY 2024-25", period: "Income earned: April 2023 – March 2024" },
  { value: "AY 2023-24", label: "AY 2023-24", period: "Income earned: April 2022 – March 2023" },
];
